### ISSUE TITLE
[help wanted] Problem installing via pip

### ISSUE THREAD

**Issue by cr8mtdev** [opulentfox-29/protonmail-api-client#21]
https://github.com/opulentfox-29/protonmail-api-client/blob/06183477fc716dd57436ad099b88be38094b00d2/src/protonmail/pgp.py#L92-L112

There might be an error with the encryption process. I just installed your project and tried to send an email according to your examples in the README. I can see that there are a lot of unfinished drafts in my mail account that could not be sent.

The Stacktrace i am getting is the following:

```
login success
/dummy/path/.local/lib/python3.11/site-packages/pgpy/constants.py:192: CryptographyDeprecationWarning: IDEA has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.IDEA and will be removed from this module in 45.0.0.
  bs = {SymmetricKeyAlgorithm.IDEA: algorithms.IDEA,
/dummy/path/.local/lib/python3.11/site-packages/pgpy/constants.py:193: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  SymmetricKeyAlgorithm.TripleDES: algorithms.TripleDES,
/dummy/path/.local/lib/python3.11/site-packages/pgpy/constants.py:194: CryptographyDeprecationWarning: CAST5 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.CAST5 and will be removed from this module in 45.0.0.
  SymmetricKeyAlgorithm.CAST5: algorithms.CAST5,
/dummy/path/.local/lib/python3.11/site-packages/pgpy/constants.py:195: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
  SymmetricKeyAlgorithm.Blowfish: algorithms.Blowfish,
Traceback (most recent call last):
  File "/dummy/path/proton.py", line 26, in <module>
    sent_message = proton.send_message(new_message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/protonmail/client.py", line 252, in send_message
    multipart = self._multipart_encrypt(message)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/protonmail/client.py", line 870, in _multipart_encrypt
    body_message, session_key = self.pgp.encrypt_with_session_key(prepared_body)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/protonmail/pgp.py", line 112, in encrypt_with_session_key
    encrypted_message = page.evaluate(f'encryptMessage({args})')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 8701, in evaluate
    self._sync(
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/_impl/_page.py", line 395, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 277, in evaluate
    await self._channel.send(
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/dummy/path/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Error: readPrivateKey: must pass options object containing `armoredKey` or `binaryKey`
```

I guess there is something wrong with the PGP-Encryption.

**Comment by opulentfox-29** [comment]
This line talks about working with javascript via playwright
`encrypted_message = page.evaluate(f'encryptMessage({args})')`
this was removed in version 1.3.5, latest version is 1.6.0, update your version:
```
pip install protonmail-api-client==1.6.0
```

**Comment by cr8mtdev** [comment]
I tried that using python3.11 and python3.10 and i can not install it:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting protonmail-api-client==1.6.0
  Using cached protonmail-api-client-1.6.0.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/68/f6/e286533af2336fb61fcae85994f835457f99e97b9664a6364647b6e4a03a/protonmail-api-client-1.6.0.tar.gz#sha256=bfaa6a724b870aa89fdd19a24ef471326004000d572ff43d7bde5e5b8e34cdf4 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/68/f6/e286533af2336fb61fcae85994f835457f99e97b9664a6364647b6e4a03a/protonmail-api-client-1.6.0.tar.gz#sha256=bfaa6a724b870aa89fdd19a24ef471326004000d572ff43d7bde5e5b8e34cdf4 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement protonmail-api-client==1.6.0 (from versions: 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0)
ERROR: No matching distribution found for protonmail-api-client==1.6.0
```

**Comment by cr8mtdev** [comment]
So i removed the package completely and reinstalled it. During the installation process you can see that pip tries to install 1.6.0 but it can not so it tries every version until it founds a working version and that is 1.3.4

```
Defaulting to user installation because normal site-packages is not writeable
Collecting protonmail-api-client
  Using cached protonmail-api-client-1.6.0.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/68/f6/e286533af2336fb61fcae85994f835457f99e97b9664a6364647b6e4a03a/protonmail-api-client-1.6.0.tar.gz#sha256=bfaa6a724b870aa89fdd19a24ef471326004000d572ff43d7bde5e5b8e34cdf4 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/68/f6/e286533af2336fb61fcae85994f835457f99e97b9664a6364647b6e4a03a/protonmail-api-client-1.6.0.tar.gz#sha256=bfaa6a724b870aa89fdd19a24ef471326004000d572ff43d7bde5e5b8e34cdf4 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
  Using cached protonmail-api-client-1.5.1.tar.gz (56 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/ff/85/5f08812802805230082718fe49d9d61a3af8d91f282f726c0b4a66903463/protonmail-api-client-1.5.1.tar.gz#sha256=7532f174c2aaec8cfbb33ff2ca1c59d6e6c8fae356efc58ac1b5d8153966ccc3 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/ff/85/5f08812802805230082718fe49d9d61a3af8d91f282f726c0b4a66903463/protonmail-api-client-1.5.1.tar.gz#sha256=7532f174c2aaec8cfbb33ff2ca1c59d6e6c8fae356efc58ac1b5d8153966ccc3 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
  Using cached protonmail-api-client-1.5.0.tar.gz (56 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/22/50/00a49fb4a0db2b020a4bde105cb938fd5b0f051f19ab2bb2659e829c51df/protonmail-api-client-1.5.0.tar.gz#sha256=96d4a9d1407d0e13b838ae26a85873374aba13c07e8934c620b72e419418dca4 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/22/50/00a49fb4a0db2b020a4bde105cb938fd5b0f051f19ab2bb2659e829c51df/protonmail-api-client-1.5.0.tar.gz#sha256=96d4a9d1407d0e13b838ae26a85873374aba13c07e8934c620b72e419418dca4 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
  Using cached protonmail-api-client-1.4.1.tar.gz (56 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/f7/13/29b7a54dd78d9b2a95568ed75f2d32758039b56ab04ff77ffbb28e46eea1/protonmail-api-client-1.4.1.tar.gz#sha256=3e86d369831811fba526f565e1bd950b80a2fbb2878ae93d8cc44f283ffcbed1 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/f7/13/29b7a54dd78d9b2a95568ed75f2d32758039b56ab04ff77ffbb28e46eea1/protonmail-api-client-1.4.1.tar.gz#sha256=3e86d369831811fba526f565e1bd950b80a2fbb2878ae93d8cc44f283ffcbed1 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
  Using cached protonmail-api-client-1.4.0.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/57/e7/54cb34cc3cd7acf3deb883df7601a4ef493ed35821d145f894bf82e6db58/protonmail-api-client-1.4.0.tar.gz#sha256=d4d49cc59cb2b35781b87203af0196089686bf215d885cf8fa950468159b5b85 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/57/e7/54cb34cc3cd7acf3deb883df7601a4ef493ed35821d145f894bf82e6db58/protonmail-api-client-1.4.0.tar.gz#sha256=d4d49cc59cb2b35781b87203af0196089686bf215d885cf8fa950468159b5b85 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
  Using cached protonmail-api-client-1.3.5.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package protonmail-api-client produced metadata for project name unknown. Fix your #egg=protonmail-api-client fragments.
Discarding https://files.pythonhosted.org/packages/a8/1b/f0e1033b25cc5006a8e9d08b986bd86a088bbc7317cb04bd329f2be399d7/protonmail-api-client-1.3.5.tar.gz#sha256=204b603d3309be7a7c624c1725674f8be55ed647b6cfab488879529ccfaa2a17 (from https://pypi.org/simple/protonmail-api-client/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/a8/1b/f0e1033b25cc5006a8e9d08b986bd86a088bbc7317cb04bd329f2be399d7/protonmail-api-client-1.3.5.tar.gz#sha256=204b603d3309be7a7c624c1725674f8be55ed647b6cfab488879529ccfaa2a17 has inconsistent name: filename has 'protonmail-api-client', but metadata has 'unknown'
  Using cached protonmail_api_client-1.3.4-py3-none-any.whl (44 kB)
Requirement already satisfied: bcrypt in /usr/lib/python3/dist-packages (from protonmail-api-client) (3.2.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from protonmail-api-client) (2.25.1)
Requirement already satisfied: playwright in ./.local/lib/python3.11/site-packages (from protonmail-api-client) (1.37.0)
Requirement already satisfied: pycryptodome in ./.local/lib/python3.11/site-packages (from protonmail-api-client) (3.20.0)
Requirement already satisfied: tqdm in ./.local/lib/python3.11/site-packages (from protonmail-api-client) (4.66.4)
Requirement already satisfied: PGPy in ./.local/lib/python3.11/site-packages (from protonmail-api-client) (0.6.0)
Requirement already satisfied: requests-toolbelt in ./.local/lib/python3.11/site-packages (from protonmail-api-client) (1.0.0)
Requirement already satisfied: aiohttp in ./.local/lib/python3.11/site-packages (from protonmail-api-client) (3.10.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in ./.local/lib/python3.11/site-packages (from aiohttp->protonmail-api-client) (2.3.2)
Requirement already satisfied: aiosignal>=1.1.2 in ./.local/lib/python3.11/site-packages (from aiohttp->protonmail-api-client) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.11/site-packages (from aiohttp->protonmail-api-client) (1.9.4)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp->protonmail-api-client) (21.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.local/lib/python3.11/site-packages (from aiohttp->protonmail-api-client) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.11/site-packages (from aiohttp->protonmail-api-client) (6.0.5)
Requirement already satisfied: pyasn1 in ./.local/lib/python3.11/site-packages (from PGPy->protonmail-api-client) (0.6.0)
Requirement already satisfied: cryptography>=3.3.2 in ./.local/lib/python3.11/site-packages (from PGPy->protonmail-api-client) (43.0.0)
Requirement already satisfied: greenlet==2.0.2 in ./.local/lib/python3.11/site-packages (from playwright->protonmail-api-client) (2.0.2)
Requirement already satisfied: pyee==9.0.4 in ./.local/lib/python3.11/site-packages (from playwright->protonmail-api-client) (9.0.4)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.11/site-packages (from pyee==9.0.4->playwright->protonmail-api-client) (4.12.2)
Requirement already satisfied: cffi>=1.12 in ./.local/lib/python3.11/site-packages (from cryptography>=3.3.2->PGPy->protonmail-api-client) (1.16.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->protonmail-api-client) (3.3)
Requirement already satisfied: pycparser in ./.local/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=3.3.2->PGPy->protonmail-api-client) (2.22)
Installing collected packages: protonmail-api-client
Successfully installed protonmail-api-client-1.3.4
```

**Comment by opulentfox-29** [comment]
Looks like a problem in your system. The possibility of installation was checked on Windows, macOS, Ubuntu.
Tell me what operating system, processor, pip version, setuptools version you have?
Try updating pip and setuptools:
```
python -m pip install --upgrade pip
```
```
pip install --upgrade setuptools
```
Also some say that for pip to work correctly on macOS you need to install cmake

**Comment by cr8mtdev** [comment]
So first i would like to apologize for the probably misleading title. I thought it was a problem with the encryption process.

I am using Ubuntu 22.04 LTS. I could get it to work now. What did it for me was upgrading pip i guess because i have different setuptools versions installed but i could always install **protonmail-api-client 1.6.0**. I tried the following python installations:

python3.10.12
setuptools               59.6.0
pip                      24.2

python3.11
setuptools            72.1.0
pip                   24.2

Virtualenvironment python3.11 (created with python3.11 -m venv .YOUR_VENV_FOLDER)
setuptools            72.1.0
pip                   24.2

Before i had some version of pip 22.x installed.

So - glad you could help me!

**Comment by opulentfox-29** [comment]
On Linux with `pip<23` this project could not be installed and the project version was automatically downgraded to `1.3.4`, which had wheel in the build, this happened, for example, on default Ubuntu 22.04

In the new version `1.7.2` I included wheel, so now everyone can install new versions
